
import { Meal, Plan } from './types';

export const MEALS: Meal[] = [
  {
    id: 'm1',
    name: 'Grilled Salmon with Quinoa',
    calories: 450,
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=400',
    description: 'Fresh Atlantic salmon served over a bed of fluffy quinoa and roasted vegetables.',
    available: true,
  },
  {
    id: 'm2',
    name: 'Roasted Mediterranean Tofu',
    calories: 380,
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400',
    description: 'Crispy tofu cubes tossed with olives, cherry tomatoes, and cucumber.',
    available: true,
  },
  {
    id: 'm3',
    name: 'Lemon Herb Chicken Breast',
    calories: 420,
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=400',
    description: 'Tender chicken breast marinated in lemon and fresh rosemary.',
    available: true,
  },
  {
    id: 'm4',
    name: 'Sweet Potato Buddha Bowl',
    calories: 510,
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=400',
    description: 'Roasted sweet potato, chickpeas, kale, and avocado with tahini dressing.',
    available: true,
  },
  {
    id: 'm5',
    name: 'Lean Beef & Broccoli Stir-fry',
    calories: 480,
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1512058560366-cd2429598a6e?auto=format&fit=crop&q=80&w=400',
    description: 'High-protein lean beef strips with fresh broccoli and ginger soy sauce.',
    available: true,
  },
  {
    id: 'm6',
    name: 'Lentil & Spinach Curry',
    calories: 350,
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&q=80&w=400',
    description: 'Hearty lentils simmered in a coconut curry base with fresh spinach.',
    available: true,
  },
  {
    id: 'm7',
    name: 'Zucchini Noodles with Pesto',
    calories: 290,
    isVeg: true,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=400',
    description: 'Light and fresh zucchini noodles with homemade basil pesto and pine nuts.',
    available: true,
  },
  {
    id: 'm8',
    name: 'Turkey & Cranberry Salad',
    calories: 410,
    isVeg: false,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=400',
    description: 'Shredded roasted turkey with dried cranberries, walnuts, and mixed greens.',
    available: true,
  },
];

export const PLANS: Plan[] = [
  {
    id: 'plan_5',
    name: '5-Meal Plan',
    price: 66,
    mealLimit: 5,
    extraPrice: 12.90,
  },
  {
    id: 'plan_10',
    name: '10-Meal Plan',
    price: 121,
    mealLimit: 10,
    extraPrice: 11.90,
    badge: 'Best Value',
  },
];
